HMS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static
 
urlpatterns = [
    path('admin/', admin.site.urls),

    # Custom URLS
    path("user/", include("userauths.urls")),
    path("", include("hotel.urls")),
    path("booking/", include("booking.urls")),
    path("dashboard/", include("user_dashboard.urls")),

    # Ckeditor
    path("ckeditor5/", include("django_ckeditor_5.urls")) 
 
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

booking/urls.py
from django.urls import path 
from booking import views 

app_name = "booking"

urlpatterns = [
    path("check_room_availability/", views.check_room_availability, name="check_room_availability"),
    path("booking/add_to_selection/", views.add_to_selection, name="add_to_selection"),
    
    path("add_to_selection/", views.add_to_selection, name="add_to_selection"),
    path("delete_selection/", views.delete_selection, name="delete_selection"),
    
]

hotel/urls.py
from django.urls import path,include 

from hotel import views

app_name = "hotel"

urlpatterns = [
    path("", views.index, name="index"),
    path("detail/<slug:slug>/", views.hotel_detail, name="hotel_detail"),
    path("detail/<slug:slug>/room-type/<slug:rt_slug>/", views.room_type_detail, name="room_type_detail"),
    path("selected_rooms/", views.selected_rooms,name="selected_rooms"),
    path("checkout/<booking_id>/", views.checkout, name="checkout"),
    path("update_room_status/", views.update_room_status, name="update_room_status"),
    path("hotelier_add_hotel/", views.hotelier_add_hotel, name="hotelier_add_hotel"),
    path('search-hotels/', views.search_hotels_view, name='hotel_hotels'),

    # Payment Routes
    path('api/create_checkout_session/<booking_id>/', views.create_checkout_session, name='api_checkout_session'),
    path('success/<str:booking_id>/', views.payment_success, name='success'),
    path('failed/<booking_id>/', views.payment_failed, name='failed'),
]

user_dashboard/urls.py
from django.urls import path 


from user_dashboard import views
from django.contrib.auth import views as auth_views

app_name = "user_dashboard"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("booking-detail/<booking_id>/", views.booking_detail, name="booking_detail"),
    path("bookings/", views.bookings, name="bookings"),
    path("notifications/", views.notifications, name="notifications"),
    path("notification_mark_as_seen/<id>/", views.notification_mark_as_seen, name="notification_mark_as_seen"),
    path("wallet/", views.wallet, name="wallet"),
    path("bookmark/", views.bookmark, name="bookmark"),
    path("delete_bookmark/<bid>/", views.delete_bookmark, name="delete_bookmark"),
    path("add_to_bookmark/", views.add_to_bookmark, name="add_to_bookmark"),
    path("profile/", views.profile, name="profile"),

    # Change Password View
    path('change-password/',auth_views.PasswordChangeView.as_view(template_name='user_dashboard/password-reset/change-password.html',success_url = '/dashboard/password-changed/'),name='change_password'),
    path("password-changed/", views.password_changed, name="password_changed"),
    path("add_review/", views.add_review, name="add_review"),
]

hotel/views.py
from django.shortcuts import render,redirect
from hotel.models import Hotel, Booking, ActivityLog, StaffOnDuty, Room, RoomType, HotelGallery, HotelFeatures, Notification, HotelFaqs, Coupon, Bookmark, Review
from django.contrib import messages
from django.http import JsonResponse
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.utils import timezone


from decimal import Decimal
from django.conf import settings
import stripe

from django.urls  import reverse


from datetime import datetime

from hotel.management.commands.update_coordinates import geocode_address
# def get_nearby_hotels_by_address(address, radius=5000):
#     lat, lon = geocode_address(address)
#     if lat and lon:
#         hotels = Hotel.objects.raw('''
#             SELECT * FROM yourapp_hotel
#             WHERE ST_DistanceSphere(POINT(longitude, latitude), POINT(%s, %s)) < %s
#         ''', [lon, lat, radius])
#         return hotels
#     return None

def index(request):
    hotels = Hotel.objects.filter(status="Live")
    context = {
        "hotels":hotels
    }
    return render(request, "hotel/hotel.html",  context)

# Create your views here.

def hotel_detail(request, slug):
    hotel = Hotel.objects.get(status="Live", slug=slug)

    if request.user.is_authenticated:
        bookmark = Bookmark.objects.filter(user=request.user, hotel=hotel)
    else:
        bookmark = None

    all_reviews = Review.objects.filter(hotel=hotel)

    try:
        reviews = Review.objects.filter(user=request.user, hotel=hotel)
    except:
        reviews = None
    

    context = {
        "hotel":hotel,
        "bookmark":bookmark,
        "reviews":reviews,
        "all_reviews":all_reviews,
     }
    return render(request, 'hotel/hotel_detail.html', {'hotel': hotel})
    # return render(request, "hotel/hotel_detail.html", context)


def room_type_detail(request, slug, rt_slug):
    hotel = Hotel.objects.get(status="Live", slug=slug)
    room_type = RoomType.objects.get(hotel=hotel, slug=rt_slug)
    rooms = Room.objects.filter(room_type=room_type, is_available=True)

    id = request.GET.get("hotel-id")
    checkin = request.GET.get("checkin")
    checkout = request.GET.get("checkout")
    adult = request.GET.get("adult")
    children = request.GET.get("children")
    room_type_ = request.GET.get("room-type")

    print("ID ==========", id)

    if not all([checkin, checkout]):
        messages.warning(request, "Please enter your booking data to check availability.")
        return redirect("booking:booking_data", hotel.slug)

    context = {
         "hotel":hotel,
         "room_type":room_type,
         "rooms":rooms,
         "checkin":checkin,
         "checkout":checkout,
         "adult":adult,
         "children":children,
         "id":id,
         "room_type_":room_type_,
    }
    
    return render(request, "hotel/room_type_detail.html", context)

def selected_rooms(request):
    total = 0  
    room_count = 0
    total_days = 0
    adult = 0 
    children = 0 
    checkin = "" 
    checkout = "" 
    children = 0 
    
    if 'selection_data_obj' in request.session:
        if request.method == "POST":
            for h_id, item in request.session['selection_data_obj'].items():
                id = int(item['hotel_id'])
                # hotel_id = int(item['hotel_id'])
                checkin = item["checkin"]
                checkout = item["checkout"]
                adult = int(item["adult"])
                children = int(item["children"])
                room_type_ = item["room_type"]
                room_id = int(item["room_id"])
                
                user = request.user
                hotel = Hotel.objects.get(id=id)
                room = Room.objects.get(id=room_id)
                room_type = RoomType.objects.get(id=room_type_)

            date_format = "%Y-%m-%d"
            checkin_date = datetime.strptime(checkin, date_format)
            checout_date = datetime.strptime(checkout, date_format)
            time_difference = checout_date - checkin_date
            total_days = time_difference.days

            full_name = request.POST.get("full_name")
            email = request.POST.get("email")
            phone = request.POST.get("phone")

            booking = Booking.objects.create(
                hotel=hotel,
                room_type=room_type,
                check_in_date=checkin,
                check_out_date=checkout,
                total_days=total_days,
                num_adults=adult,
                num_children=children,
                full_name=full_name,
                email=email,
                phone=phone,
                user=request.user or None,
                payment_status = "Processing",
            )

            if request.user.is_authenticated:
                booking.user = request.user
                booking.save()
            else:
                booking.user = None
                booking.save()

            for h_id, item in request.session['selection_data_obj'].items():
                room_id = int(item["room_id"])
                room = Room.objects.get(id=room_id)
                booking.room.add(room)

                room_count += 1
                days = total_days
                price = room_type.price

                room_price = price * room_count
                total = room_price * days

            booking.total += float(total)
            booking.before_discount += float(total)
            booking.save()

            messages.success(request, "Checkout Now!")
            return redirect("hotel:checkout", booking.booking_id)

        hotel = None
        for h_id, item in request.session['selection_data_obj'].items():
            id = int(item['hotel_id'])
            hotel_id = int(item['hotel_id'])

            checkin = item["checkin"]
            checkout = item["checkout"]
            adult = int(item["adult"])
            children = int(item["children"])
            room_type_ = item["room_type"]
            room_id = int(item["room_id"])  

            # user = request.user
            # hotel = Hotel.objects.get(id=id)
            # room = Room.objects.get(id=room_id)
            room_type = RoomType.objects.get(id=room_type_)

            date_format = "%Y-%m-%d"
            checkin_date = datetime.strptime(checkin, date_format)
            checout_date = datetime.strptime(checkout, date_format)
            time_difference = checout_date - checkin_date
            total_days = time_difference.days 

            room_count += 1
            days = total_days
            price = room_type.price 

            room_price = price * room_count
            total = room_price * days

            hotel = Hotel.objects.get(id=id)
        
        context = {
            "data":request.session['selection_data_obj'], 
            "total_selected_items": len(request.session['selection_data_obj']),
            "total":total,
            "total_days":total_days,
            "adult":adult,
            "children":children,   
            "checkin":checkin,   
            "checkout":checkout,   
            "hotel":hotel,   
        }
        return render (request, "hotel/selected_rooms.html", context)

                   
    else:
        messages.warning(request, "No selected rooms yet")
        return redirect("/")

# def checkout(request, booking_id):
#     booking = Booking.objects.get(booking_id=booking_id)
#     if request.method == "POST":
#         code = request.POST.get("code")
#         try:
#             coupon = Coupon.objects.get(code__iexact=code, active=True)
#             if coupon in booking.coupons.all():
#                 messages.warning(request, "Coupon Already Activated")
#                 return redirect("hotel:checkout", booking.booking_id)
#             else:
#                 if coupon.type == "Percentage":
#                     discount = booking.total * coupon.discount / 100
#                 else:
#                     discount = coupon.discount

#                     booking.coupons.add(coupon)
#                     booking.total -= discount
#                     booking.saved += discount
#                     booking.save()

                
#                     messages.success(request, "Coupon Activated")
#                     return redirect("hotel:checkout", booking.booking_id)
#         except:
#             messages.error(request, "Coupon Does Not Exists")
#             return redirect("hotel:checkout", booking.booking_id)
#     context={
#         "booking":booking
#     }
#     return render(request, "hotel/checkout.html", context)
def checkout(request, booking_id):
    booking = Booking.objects.get(booking_id=booking_id)
    if request.method == "POST":
        code = request.POST.get("code")
        try:
            coupon = Coupon.objects.get(code__iexact=code, active=True)
            if coupon in booking.coupons.all():
                messages.warning(request, "Coupon Already Activated")
                return redirect("hotel:checkout", booking.booking_id)
            else:
                if coupon.type == "Percentage":
                    discount = booking.total * coupon.discount / 100
                else:
                    discount = coupon.discount

                booking.coupons.add(coupon)
                booking.total -= discount
                booking.saved += discount
                booking.save()

                messages.success(request, "Coupon Activated")
                return redirect("hotel:checkout", booking.booking_id)
        except Coupon.DoesNotExist:
            messages.error(request, "Coupon Does Not Exist")
            return redirect("hotel:checkout", booking.booking_id)
    context = {
        "booking": booking,


    }
    return render(request, "hotel/checkout.html", context)

def payment_success(request, booking_id):

templates/hotel/hotelier_add_hotel.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}


  <div class="container mt-5">
    <h2>Add a New Hotel</h2>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.non_field_errors }}
      <div class="form-group">
        {{ form.name.label_tag }}
        {{ form.name }}
        {{ form.name.errors }}
      </div>
      <div class="form-group">
        {{ form.description.label_tag }}
        {{ form.description }}
        {{ form.description.errors }}
      </div>
      <div class="form-group">
        {{ form.image.label_tag }}
        {{ form.image }}
        {{ form.image.errors }}
      </div>
      <div class="form-group">
        {{ form.address.label_tag }}
        {{ form.address }}
        {{ form.address.errors }}
      </div>
      <div class="form-group">
        {{ form.mobile.label_tag }}
        {{ form.mobile }}
        {{ form.mobile.errors }}
      </div>
      <div class="form-group">
        {{ form.email.label_tag }}
        {{ form.email }}
        {{ form.email.errors }}
      </div>
      <div class="form-group">
        {{ form.status.label_tag }}
        {{ form.status }}
        {{ form.status.errors }}
      </div>
      <div class="form-group">
        {{ form.tags.label_tag }}
        {{ form.tags }}
        {{ form.tags.errors }}
      </div>
      <div class="form-group form-check">
        {{ form.featured }}
        {{ form.featured.label_tag }}
        {{ form.featured.errors }}
      </div>
      <button type="submit" class="btn btn-primary">Add Hotel</button>
    </form>
  </div>

{% endblock content %}

templates/hotel/payment_success.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
  
  <div class="not_found_block">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <section id="not-found" class="center">
            <h2 class="margin-bottom-10"><i class="fa fa-check-circle" style="color: green;"></i></h2>

            <p style="margin-top: 10px; color: black;"><b>Checkout & Payment Successfull!</b></p>
            <div class="utf_error_description_part utf_ferror_description">  
                <span class="f-primary animated v fadeInRight">Your booking summary is in your dashboard. Your booking id is <b>{{booking.booking_id}}</b> Thank you.</span> 
            </div>
            <div><a href="{% url 'user_dashboard:profile' %}">

              <button type="submit" class="button utf_booking_confirmation_button margin-top-20 w-100 " style="background-color: orange; color: rgb(37, 28, 3);">Proceed To Your Dashboard.</button></a>	
            </div>
            {% comment %} <a href="{% url 'hotel:invoice' booking.booking_id %}" class="button margin-top-20">Visit Dashboard</a> {% endcomment %}
            {% comment %} <a href="{% url 'hotel:invoice' booking.booking_id %}" target="_blank" class="button margin-top-20">View Invoice 🧾</a> {% endcomment %}
            <div class="row">
              <div class="col-lg-6 col-lg-offset-3">
                <div class="gray-style margin-top-50 margin-bottom-10">
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/hotel/room_type_detail.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
  
  <div id="titlebar" class="gradient">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>{{room_type.type}} Room</h2>
          <nav id="breadcrumbs">
            <ul>
              <li><p>{{rooms.count}} Available Rooms</p></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>

  
  <section class="fullwidth_block margin-top-0 padding-top-0 padding-bottom-50" data-background-color="#fff"> 
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h3 class="headline_part centered margin-bottom-20">All Available Rooms<span>The {{ room_type.type }} room has {{ rooms.count }} available room(s)</span></h3>
        </div>
      </div>
      <div class="row">  
        <div class="col-lg-8 "> 
          
          {% for r in rooms %}
              <div class="plan featured col-md-4 col-sm-6 col-xs-12">
              <div class="utf_price_plan">
                  <h3>Room No. {{ r.room_number }}</h3>
                  <span class="value">₦{{r.room_type.price}}<span>/Per Night</span></span> 
              </div>
              <div class="utf_price_plan_features">
                  <ul>
                    <li>Beds: {{r.room_type.number_of_beds}} </li>
                    <li>Room Capacity: {{r.room_type.room_capacity}}</li>
                  </ul>
                  <input type="hidden" class="room_id_{{r.id}}" value="{{r.id}}" id="room_id">
                  <input type="hidden" class="room_number_{{r.id}}" value="{{r.room_number}}" id="room_number" >

                  <button class="button border add-to-selection" data-index={{r.id}}><i class="fas fa-shopping-cart"></i> Add To Selection</button> 
              </div>
              </div>
          {% endfor %}
          
          <input type="hidden" value="{{hotel.id}}" id="id">
          <input type="hidden" value="{{hotel.name}}" id="hotel_name">
          <input type="hidden" value="{{room_type.type}}" id="room_name">
          <input type="hidden" value="{{room_type.price}}" id="room_price">
          <input type="hidden" value="{{room_type.number_of_beds}}" id="number_of_beds">
          <input type="hidden" value="{{room_type.id}}" id="room_type">
          <input type="hidden" value="{{checkin}}" id="checkin">
          <input type="hidden" value="{{checkout}}" id="checkout">
          <input type="hidden" value="{{adult}}" id="adult">
          <input type="hidden" value="{{children}}" id="children">

          
        </div>  
        <div class="col-lg-4">
            <div class=" booking_widget_box" style="border: 1px dashed rgba(42, 1, 119, 0.61); padding: 14px; border-radius: 10px;">
              <h3><i class="fa fa-calendar"></i> Booking</h3>
              <form class="row with-forms margin-top-0" method="POST" action="">
                  {% csrf_token %}
                  <input type="hidden" value="{{hotel.id}}" name="hotel-id" id="">
                  <div class="col-lg-12 col-md-12 select_date_box">
                      <label for="">Check-in Date</label>
                      <input type="date" id="date-picker" value="{{checkin}}" name="checkin" placeholder="Select Date">
                  </div>
                  <div class="col-lg-12 col-md-12 select_date_box">
                      <label for="">Check-out Date</label>
                      <input type="date" class="checkout_date" name="checkout" value="{{checkout}}"  placeholder="Select Date">
                  </div>
                  <div class="with-forms">
                      <div class="col-lg-12 col-md-12">
                          <a href="#">Guests <span class="qtyTotal" name="qtyTotal">1</span></a>
                          <div class="panel-dropdown-content">
                              <div class="qtyButtons">
                                  <div class="qtyTitle">Adults</div>
                                  <input type="text" name="adult" {% if adult == None %}value="1"{% else %}value="{{adult}}"{% endif %}>
                              </div>
                              <div class="qtyButtons">
                                  <div class="qtyTitle">Childrens</div>
                                  <input type="text" name="children" {% if children == None %}value="1"{% else %}value="{{children}}"{% endif %}>
                              </div>
                          </div>
                      </div>
                  </div>

                  <div class="with-forms margin-top-30">
                      <div class="col-lg-12 col-md-12 ">
                          <a href="#">Select Room Type</a>
                          <select name="room-type" class="utf_chosen_select_single" required>
                              <!-- <option value="{{room_type|lower}}">{{room_type}}</option> -->
                              <option value="{{room_type|lower}}">{{room_type}}</option>

                              {% for r in hotel.hotel_room_types %}
                                  <option value="{{r.slug}}">{{r.type}}</option>
                              {% endfor %}
                            </select>
                      </div>
                  </div>
                
                  <button type="submit" class="utf_progress_button button fullwidth_block margin-top-5">Check Availability</button>
              </form>
              <button class="like-button add_to_wishlist"><span class="like-icon"></span> Add to Wishlist</button>
              <div class="clearfix"></div>
            </div>
        </div>      
              
      </div>      
    </div>    
  </section>

  <script>
    $(document).ready(function(){
        
        var dateInput = $('#checkout_date');

        dateInput.on('change', function() {
            var selectedDate = dateInput.val();
            console.log('Selected date:', selectedDate);
        });
    })
  </script>
  {% comment %} <script>
    var addToSelectionUrl = "{% url 'hotel:add_to_selection' %}";
  </script> {% endcomment %}
  
{% endblock content %}

templates/hotel/selected_rooms.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
  
<div id="main_wrapper" class="selection-list">
  
  <div id="titlebar" class="gradient">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>All Room Selections</h2>
          <nav id="breadcrumbs">
            <ul>
              <li><a>Home</a></li>
              <li><a>Hotel</a></li>
              <li><a>Rooms</a></li>
              <li>My selected rooms</li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
  
  <div class="container margin-bottom-75">
    <div class="row">
      <div class="col-lg-8 col-md-8 utf_listing_payment_section">
	    
        <div class="utf_booking_listing_section_form margin-bottom-40">
            <h3><i class="fas fa-bed"></i> Selected Rooms</h3>
            <div class="utf_listing_section">
                    <div class="utf_pricing_list_section">
                        <ul>
                            {% for id, item in data.items %}
                                <li>
                                    <h5>Room: {{item.room_name}} 
                                      <small>
                                        <a style="cursor: pointer;" class="delete-item" data-item="{{ id }}"><i class="fas fa-trash" style="color: red;"></i></a>
                                      </small> 
                                    </h5>
                                    <p><strong>Beds :</strong> {{item.number_of_beds}}  </p>
                                    <span>₦{{item.room_price}} </span>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
            </div>
        </div>
        <div class="utf_booking_listing_section_form margin-bottom-40">
            <h3><i class="fas fa-check-circle"></i> Update Selection</h3>
            <div class="utf_listing_section">
                    <div class="utf_pricing_list_section">
                      <form class="row with-forms margin-top-0" method="POST" action="{% url 'booking:check_room_availability' %}">
                        {% csrf_token %}
                        <input type="hidden" value="{{hotel.id}}" name="hotel-id" id="">
                        <div class="col-lg-12 col-md-12 select_date_box">
                            <label for="">Check-in Date</label>
                            <input type="date" id="date-picker" value="{{checkin}}" name="checkin" placeholder="Select Date">
                        </div>
                        <div class="col-lg-12 col-md-12 select_date_box">
                            <label for="">Check-out Date</label>
                            <input type="date" name="checkout" value="{{checkout}}" id="date-picker" placeholder="Select Date">
                        </div>
                        <div class="with-forms">
                            <div class="col-lg-12 col-md-12">
                                <a href="#">Guests <span class="qtyTotal" style="visibility: hidden;" name="qtyTotal"></span></a>
                                <div class="panel-dropdown-content">
                                    <div class="qtyButtons">
                                        <div class="qtyTitle">Adults</div>
                                        <input type="text" name="adult" {% if adult == None %}value="1"{% else %}value="{{adult}}"{% endif %}>
                                    </div>
                                    <div class="qtyButtons">
                                        <div class="qtyTitle">Childrens</div>
                                        <input type="text" name="children" {% if children == None %}value="1"{% else %}value="{{children}}"{% endif %}>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <a style="margin-top: 50px;">Select Room Type (*required) </a>
                        <select name="room-type">
                            <option value="">Select Room</option>
                            
                            {% for r in hotel.hotel_room_types %}
                                <option value="{{r.slug}}">{{r.type}}</option>
                            {% endfor %}
                        </select>
                      
                        <button type="submit" class="utf_progress_button button fullwidth_block margin-top-5"> <i class="fas fa-check-circle"></i> Update Selection </button>
                    </form>
                    </div>
            </div>
        </div>
            
      <form class="utf_booking_listing_section_form margin-bottom-40" method="POST">
        {% csrf_token %}
        <h3><i class="fas fa-user"></i> Billing Information</h3>
        <div class="row">
          <div class="col-md-12">
            <label>First Name</label>
            <input name="full_name" type="text" value="" placeholder="First Name">
          </div>
          <div class="col-md-6">
            <div class="medium-icons">
              <label>E-Mail</label>
              <input name="email" type="text" value="" placeholder="Email">
            </div>
          </div>
          <div class="col-md-6">
            <div class="medium-icons">
              <label>Phone</label>
              <input name="phone" type="text" value="" placeholder="Phone">
            </div>
          </div>
          <div class="col-lg-12">
            <button type="submit" class="button utf_booking_confirmation_button margin-top-20 margin-bottom-10">Continue to checkout <i class="fas fa-right-arrow"></i></button> 		
          </div>
        </div>
		</form>

		
	  </div>
      <div class="col-lg-4 col-md-4 margin-top-0 utf_listing_payment_section">
        <div class="utf_booking_listing_item_container compact utf_order_summary_widget_section">
          <div class="listing-item"> 
            <img src="{{hotel.image.url}}" alt="">
            <div class="utf_listing_item_content">              
              <h3>{{hotel.name}}</h3>
              <span><i class="fa fa-map-marker"></i> {{hotel.address}}</span>
						<span><i class="fa fa-phone"></i> {{hotel.mobile}}</span>											
			  <div class="utf_star_rating_section" data-rating="4.5">
				<div class="utf_counter_star_rating">(18) Reviews</div>
			  </div>
			</div>
          </div>
        </div>
        <div class="boxed-widget opening-hours summary margin-top-0">
          <h3><i class="fa fa-calendar-check-o"></i> Booking Summary</h3>
          <ul>
            <li>Check-in <span>{{checkin}}</span></li>
			<li>Check-out <span>{{checkout}}</span></li>            
			<li>Total Days <span>{{total_days}} Days</span></li>            
            <li>Adults <span>{{ adult }} Adult</span></li>
            <li>Children <span>{{ children }} Children</span></li>
			      <li>V.A.T <span>₦0.00</span></li>
            <li class="total-costs">Total Cost <span>₦{{total}}</span></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  
</div>

  
{% endblock content %}  